
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const CLEAR_ORDER_STATE= 'CLEAR_ORDER_STATE';


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_PRICE_FILTER = 'SET_PRICE_FILTER';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';


export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const FETCH_ORDERBYID_REQUEST = 'FETCH_ORDERBYID_REQUEST';
export const FETCH_ORDERBYID_SUCCESS = 'FETCH_ORDERBYID_SUCCESS';
export const FETCH_ORDERBYID_FAILURE = 'FETCH_ORDERBYID_FAILURE';

export const FETCH_ALLS_ORDERS_REQUEST = 'FETCH_ALLS_ORDERS_REQUEST';
export const FETCH_ALLS_ORDERS_SUCCESS = 'FETCH_ALLS_ORDERS_SUCCESS';
export const FETCH_ALLS_ORDERS_FAILURE = 'FETCH_ALLS_ORDERS_FAILURE';
export const UPDATE_ORDER_STATE_SUCCESS = 'UPDATE_ORDER_STATE_SUCCESS';
export const UPDATE_ORDER_STATE_FAILURE = 'UPDATE_ORDER_STATE_FAILURE';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';

export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';

export const SB_CREATE_REQUEST = 'SB_CREATE_REQUEST';
export const SB_CREATE_SUCCESS = 'SB_CREATE_SUCCESS';
export const SB_CREATE_FAIL = 'SB_CREATE_FAIL';

export const FETCH_LATEST_ORDER_REQUEST = 'FETCH_LATEST_ORDER_REQUEST';
export const FETCH_LATEST_ORDER_SUCCESS = 'FETCH_LATEST_ORDER_SUCCESS';
export const FETCH_LATEST_ORDER_FAILURE = 'FETCH_LATEST_ORDER_FAILURE';

export const FETCH_SB_REQUEST = 'FETCH_SB_REQUEST';
export const FETCH_SB_SUCCESS = 'FETCH_SB_SUCCESS';
export const FETCH_SB_FAILURE = 'FETCH_SB_FAILURE';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_SELLER_REQUEST = 'FETCH_SELLER_REQUEST';
export const FETCH_SELLER_SUCCESS = 'FETCH_SELLER_SUCCESS';
export const FETCH_SELLER_FAILURE = 'FETCH_SELLER_FAILURE';

export const CREATE_SELLER_REQUEST = 'CREATE_SELLER_REQUEST';
export const CREATE_SELLER_SUCCESS = 'CREATE_SELLER_SUCCESS';
export const CREATE_SELLER_FAILURE = 'CREATE_SELLER_FAILURE';

export const UPDATE_SELLER_REQUEST = 'UPDATE_SELLER_REQUEST';
export const UPDATE_SELLER_SUCCESS = 'UPDATE_SELLER_SUCCESS';
export const UPDATE_SELLER_FAILURE = 'UPDATE_SELLER_FAILURE';

export const SEND_INVOICE_REQUEST = 'SEND_INVOICE_REQUEST'
export const SEND_INVOICE_SUCCESS = 'SEND_INVOICE_SUCCESS'
export const SEND_INVOICE_FAILURE = 'SEND_INVOICE_FAILURE'

export const CREATE_RECEIPT_REQUEST = "CREATE_RECEIPT_REQUEST"
export const CREATE_RECEIPT_SUCCESS = "CREATE_RECEIPT_SUCCESS"
export const CREATE_RECEIPT_FAILURE = "CREATE_RECEIPT_FAILURE"

export const FETCH_LATEST_RECEIPTS_REQUEST = 'FETCH_LATEST_RECEIPTS_REQUEST';
export const FETCH_LATEST_RECEIPTS_SUCCESS = 'FETCH_LATEST_RECEIPTS_SUCCESS';
export const FETCH_LATEST_RECEIPTS_FAILURE = 'FETCH_LATEST_RECEIPTS_FAILURE';

export const FETCH_RECEIPTS_REQUEST = 'FETCH_RECEIPTS_REQUEST';
export const FETCH_RECEIPTS_SUCCESS = 'FETCH_RECEIPTS_SUCCESS';
export const FETCH_RECEIPTS_FAILURE = 'FETCH_RECEIPTS_FAILURE';

export const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST';
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
export const CREATE_EXPENSE_FAILURE = 'CREATE_EXPENSE_FAILURE';

export const GET_FILTERED_EXPENSES_REQUEST = 'GET_FILTERED_EXPENSES_REQUEST';
export const GET_FILTERED_EXPENSES_SUCCESS = 'GET_FILTERED_EXPENSES_SUCCESS';
export const GET_FILTERED_EXPENSES_FAILURE = 'GET_FILTERED_EXPENSES_FAILURE';

export const DELETE_EXPENSE_REQUEST = 'DELETE_EXPENSE_REQUEST';
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';
export const DELETE_EXPENSE_FAILURE = 'DELETE_EXPENSE_FAILURE'; 

export const CREATE_RESERVATION_REQUEST = 'CREATE_RESERVATION_REQUEST';
export const CREATE_RESERVATION_SUCCESS = 'CREATE_RESERVATION_SUCCESS';
export const CREATE_RESERVATION_FAILURE = 'CREATE_RESERVATION_FAILURE';

export const FETCH_BALANCE_REQUEST = 'FETCH_BALANCE_REQUEST';
export const FETCH_BALANCE_SUCCESS = 'FETCH_BALANCE_SUCCESS';
export const FETCH_BALANCE_FAILURE = 'FETCH_BALANCE_FAILURE';